# Generated by Django 4.2.3 on 2023-07-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('created_at', models.DateField(verbose_name='data published')),
                ('modified_at', models.DateField(verbose_name='data published')),
                ('discount', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
